In [1]:
import pandas as pd

In [2]:
Claimant_df=pd.read_csv("claimants.csv")

In [3]:
Claimant_df

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [4]:
Claimant_df.shape

(1340, 7)

In [5]:
Claimant_df.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [7]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [8]:
Claimant_df.describe()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
count,1340.000000,1340.000000,1328.000000,1299.000000,1292.000000,1151.000000,1340.000000
mean,11202.001493,0.488806,0.558735,0.907621,0.017028,28.414422,3.806307
std,9512.750796,0.500061,0.496725,0.289671,0.129425,20.304451,10.636903
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4177.000000,0.000000,0.000000,1.000000,0.000000,9.000000,0.400000
50%,8756.500000,0.000000,1.000000,1.000000,0.000000,30.000000,1.069500
75%,15702.500000,1.000000,1.000000,1.000000,0.000000,43.000000,3.781500
max,34153.000000,1.000000,1.000000,1.000000,1.000000,95.000000,173.604000

In [9]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [10]:
Claimant_df["CLMSEX"].unique()

array([ 0.,  1., nan])

In [11]:
Claimant_df["CLMSEX"]=Claimant_df["CLMSEX"].fillna(1)

In [12]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [14]:
Claimant_df['CLMINSUR'].unique()

array([ 1.,  0., nan])

In [15]:
Claimant_df["CLMINSUR"]=Claimant_df["CLMINSUR"].fillna(1)

In [16]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR      0
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [17]:
Claimant_df['SEATBELT'].unique()

array([ 0.,  1., nan])

In [18]:
Claimant_df["SEATBELT"]=Claimant_df["SEATBELT"].fillna(1)

In [19]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR      0
SEATBELT      0
CLMAGE      189
LOSS          0
dtype: int64

In [20]:
Claimant_df['CLMAGE']

0       50.0
1       18.0
2        5.0
3       31.0
4       30.0
        ...
1335     NaN
1336    46.0
1337    39.0
1338     8.0
1339    30.0
Name: CLMAGE, Length: 1340, dtype: float64

In [22]:
Claimant_df['CLMAGE'].mean()

28.414422241529106

In [23]:
Claimant_df["CLMAGE"]=Claimant_df["CLMAGE"].fillna(Claimant_df['CLMAGE'].mean())

In [24]:
Claimant_df['CLMAGE']

0       50.000000
1       18.000000
2        5.000000
3       31.000000
4       30.000000
          ...
1335    28.414422
1336    46.000000
1337    39.000000
1338     8.000000
1339    30.000000
Name: CLMAGE, Length: 1340, dtype: float64

In [25]:
Claimant_df.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [26]:
x=Claimant_df.drop(labels="ATTORNEY",axis=1)

In [27]:
x

      CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
0           5     0.0       1.0       0.0  50.000000  34.940
1           3     1.0       0.0       0.0  18.000000   0.891
2          66     0.0       1.0       0.0   5.000000   0.330
3          70     0.0       1.0       1.0  31.000000   0.037
4          96     0.0       1.0       0.0  30.000000   0.038
...       ...     ...       ...       ...        ...     ...
1335    34100     0.0       1.0       0.0  28.414422   0.576
1336    34110     1.0       1.0       0.0  46.000000   3.705
1337    34113     1.0       1.0       0.0  39.000000   0.099
1338    34145     1.0       0.0       0.0   8.000000   3.177
1339    34153     1.0       1.0       0.0  30.000000   0.688

[1340 rows x 6 columns]

In [28]:
y=Claimant_df["ATTORNEY"]

In [30]:
y

0       0
1       1
2       1
3       0
4       1
       ..
1335    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1340, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

In [78]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,shuffle=True,random_state=10)
x_train

      CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
782     10070     1.0       1.0       0.0   9.000000   0.680
414       575     0.0       1.0       0.0  14.000000   4.916
997     15574     0.0       0.0       0.0  28.414422   3.065
907     13385     0.0       1.0       0.0  39.000000   8.815
329      8418     1.0       1.0       0.0   6.000000   5.049
...       ...     ...       ...       ...        ...     ...
1180    30436     0.0       1.0       0.0  28.414422   0.098
1147    19410     0.0       0.0       0.0  51.000000  40.574
527      3748     0.0       1.0       0.0  28.414422   0.005
1149    19446     1.0       1.0       1.0   7.000000   0.156
1289    33073     1.0       1.0       0.0  41.000000   5.600

[1072 rows x 6 columns]

      CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE   LOSS
1100    18300     1.0       1.0       0.0  43.000000  3.800
592      5415     1.0       1.0       0.0  38.000000  4.977
893     13000     0.0       1.0       0.0  50.000000  1.061
431        94     1.0       1.0       0.0  28.414422  0.406
153      3667     0.0       1.0       0.0  66.000000  0.507
...       ...     ...       ...       ...        ...    ...
226      5685     1.0       1.0       0.0   6.000000  1.461
1158    19683     0.0       0.0       0.0   3.000000  0.378
187      4561     0.0       1.0       0.0  61.000000  0.307
1080    17749     1.0       1.0       0.0  38.000000  0.507
1258    31350     1.0       1.0       0.0  36.000000  6.908

[1072 rows x 6 columns]

In [41]:
x_test

      CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
535      3990     1.0       1.0       0.0   3.000000   0.843
308      7909     1.0       1.0       0.0  36.000000   0.150
839     10681     0.0       1.0       0.0  28.414422   1.000
70        607     0.0       1.0       0.0  56.000000  44.060
847     10941     0.0       1.0       0.0  10.000000   3.371
...       ...     ...       ...       ...        ...     ...
1304    33468     1.0       1.0       0.0  28.414422   0.500
1170    30017     1.0       1.0       0.0   3.000000   0.095
115      1589     0.0       1.0       0.0  28.414422   3.060
160      3800     0.0       0.0       0.0  33.000000   1.509
823     10369     0.0       1.0       0.0  28.414422   7.018

[268 rows x 6 columns]

In [42]:
y_train

1164    1
38      1
649     0
50      0
111     1
       ..
356     1
1224    0
1213    1
376     0
62      0
Name: ATTORNEY, Length: 1072, dtype: int64

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
model=LogisticRegression()

In [81]:
model.fit(x_train,y_train)

LogisticRegression()

In [82]:
y_train_pred=model.predict(x_train)

In [92]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [85]:
accuracy_score(y_train,y_train_pred)

0.7080223880597015

In [86]:
y_test_pred=model.predict(x_test)

In [87]:
accuracy_score(y_test,y_test_pred)

0.6865671641791045

In [89]:
confusion_matrix(y_test,y_test_pred)

array([[ 80,  40],
       [ 44, 104]], dtype=int64)

In [91]:
precision_score(y_test,y_test_pred)

0.7222222222222222

In [93]:
recall_score(y_test,y_test_pred)

0.7027027027027027